### ISSUE TITLE
Interesting ... but how about a container ? 

### ISSUE THREAD

**Issue by colindaven** [psipred/DMPfold#1]
Interesting idea but installation looks like the old days pre conda / singularity.

Are you thinking about providing a singularity container in the future to aid installation / make installation possible at all (for time-poor people, as in everybody) ?

Thanks,
Colin

**Comment by jgreener64** [comment]
We know installation is difficult, but it is possible and in fact is automated for Ubuntu in the [build script](https://github.com/psipred/DMPfold/blob/master/.travis.yml). A number of people have installed and are using it.

There are a few technical hurdles to overcome for us to containerise DMPfold. These include the CNS download (requires a form, password and patching), the MODELLER license key, and the download of the huge sequence database. It's something we are thinking about, but we can't promise anything.

In the meantime you are welcome to use [the server](http://bioinf.cs.ucl.ac.uk/psipred) for quick jobs, to open issues for specific installation problems, or to submit a PR with a container script or installation tips.

Of course you are right about user time, but that also applies to developer time. We have to balance making the DMPfold dependencies easy to install against developing the algorithm.

**Comment by DanBuchan** [comment]
Worth noting that many of our group's packages have large, multiple gigabyte dependencies such as uniref90 or the HHSuite DBs. Which means that containers would be either be gigantic or they would take a long time to spin up and initialise (having to pull those big files off the web).

It would indeed be nice if we had some manner of common/unified approach to installing all our software. My preference would be to provide something like a chef, puppet or ansible script. I'd rather steer away from things like containers or VMs as I'd rather leave scaling/deployment level issues to users.

We use ansible for our webserver deployment but it would require a fair bit of work extracting the relevant scripts and making sure they were standalone for each of our pieces of software. But of course that means spending developer time on it and introducing a new set of things that we have to maintain. Probably a good summer student/intern project though.

**Comment by colindaven** [comment]
Thanks for that, these are all good points. The automated build script sounds great, and I will try out the server initially too.

I'd certainly avoid VMs as well but containers - especially singularity - are just (from a user perspective) file system level images. Docker is more complex and more microservice orientated, and also not very cluster-friendly. Just as a quick aside,  the build script written isn't far off a container.

I love ansible, but it often requires an own VM / OS which it can happily destroy. Containers are very easy to delete and start again with, whereas VMs are not in many cases.
